import {
	Breadcrumb,
	BreadcrumbItem,
	BreadcrumbLink,
	BreadcrumbList,
	BreadcrumbPage,
	BreadcrumbSeparator,
} from "@pmigov/ui/components/breadcrumb";
import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/about/purchasing-terms-and-conditions")({
	component: RouteComponent,
});

const lc = "underline underline-offset-2 hover:opacity-70";

function P({ children }: { children: React.ReactNode }) {
	return (
		<p className="font-aeonik text-pmi-text-primary leading-7">{children}</p>
	);
}

function RouteComponent() {
	return (
		<main className="overflow-x-hidden" id="main-layout">
			{/* Hero */}
			<div className="w-full bg-pmi-surface-secondary">
				<div className="mx-auto max-w-screen-xl px-6 pt-6 lg:px-4">
					<Breadcrumb>
						<BreadcrumbList>
							<BreadcrumbItem>
								<BreadcrumbLink render={<Link to="/" />}>Home</BreadcrumbLink>
							</BreadcrumbItem>
							<BreadcrumbSeparator />
							<BreadcrumbItem>
								{/* biome-ignore lint/a11y/useAnchorContent: TanStack BreadcrumbLink render prop — content is in children */}
								<BreadcrumbLink render={<a href="/about" />}>
									What We Do
								</BreadcrumbLink>
							</BreadcrumbItem>
							<BreadcrumbSeparator />
							<BreadcrumbItem>
								<BreadcrumbPage>Purchasing Terms and Conditions</BreadcrumbPage>
							</BreadcrumbItem>
						</BreadcrumbList>
					</Breadcrumb>
				</div>
				<div className="mx-auto max-w-screen-xl px-6 pt-20 pb-16 sm:pt-24 sm:pb-20 lg:px-4">
					<h1 className="mb-6 font-aeonik font-bold text-header-md text-pmi-text-primary sm:text-header-xl">
						Purchasing Terms and Conditions
					</h1>
				</div>
			</div>

			{/* Content card */}
			<div
				className="relative w-full overflow-hidden bg-pmi-surface-primary"
				style={{
					borderRadius: "var(--pmi-rounded-md) var(--pmi-rounded-md) 0 0",
					marginTop: "calc(-1 * var(--pmi-rounded-md))",
				}}
			>
				<div className="mx-auto max-w-screen-xl px-6 py-6 lg:px-4 lg:py-10">
					<ol className="list-decimal space-y-8 pl-6">
						{/* 1 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								PURPOSE AND SCOPE
							</p>
							<P>
								This establishes the Master Terms and Conditions ("MTC") that
								govern the supply of goods, equipment and materials ("Goods")
								and the provision of services ("Services") to Project Management
								Institute, Inc. ("PMI" or "Buyer") by suppliers (each a
								"Supplier"). PMI and Supplier are referred to individually as a
								"Party" or collectively as the "Parties".
							</P>
						</li>

						{/* 2 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								DEFINITIONS
							</p>
							<div className="space-y-2 font-aeonik text-pmi-text-primary leading-7">
								<P>
									<em>"Affiliate"</em> means each of the Parties' subsidiaries,
									the Party's or its subsidiary's holding company, and any
									subsidiary of a Party or its subsidiary's holding company.
								</P>
								<P>
									<em>"Buyer Data"</em> means: (i) all data in any form provided
									by Buyer to Supplier, or (as applicable) entered in or used in
									conjunction with any software or platform provided by Supplier
									to Buyer, Buyer's authorized Affiliates and Buyer's Users;
									(ii) Buyer's Customers', Employees' or Users' personal
									identification information, and (iii) any and all input,
									feedback, responses, or other communications directed to Buyer
									by Buyer's Users or Customers, by any means, including without
									limitation by, through or using Supplier software or platform
									and (iv) any reporting, analysis, or recommendations
									incorporating or related to any Customer or User input,
									feedback, responses or communications generated by Supplier
									and provided to Buyer.
								</P>
								<P>
									<em>"Change Order"</em> means a written modification to the
									Goods or Services as described in a Purchase Order, Statement
									of Work or Order Form, approved and signed by authorized
									representatives of the Parties, and incorporated into the
									Purchase Order, Statement of Work or Order Form.
								</P>
								<P>
									<em>"Contract"</em> means: (i) a Purchase Order incorporating
									these terms and conditions (which include the Data Processing
									Agreement, the Service Level Agreement, and the FARS
									Regulations, when applicable) and any Amendment or Addenda or
									(ii) this MTC, along with any Amendment, Addenda, Statement of
									Work, Order Form, Change Order, or other authorized
									documentation that together constitute the full agreement of
									the Parties.
								</P>
								<P>
									"Customer" means a natural or corporate person who: (i) has
									obtained or is seeking to obtain any form of product or
									service from Buyer, including without limitation publications,
									memberships, certification examinations, training, online or
									in-person event access, awards, informational materials or
									licensing rights; or (ii) has visited a website published or
									sponsored by Buyer; or (iii) has responded to a solicitation,
									survey, invitation, or other outreach by Buyer.
								</P>
								<P>
									<em>"Data Controller"</em> means the entity that determines
									the purposes and means of the Processing of Personal Data.
								</P>
								<P>
									<em>"Data Processor"</em> means the entity which Processes
									Personal Data on behalf of the Data Controller.
								</P>
								<P>
									<em>"Data Subject"</em> means the individual to whom Personal
									Data relates.
								</P>
								<P>
									<em>"Deliverables"</em> means all Goods and Services
									identified in the Contract.
								</P>
								<P>
									<em>"Designated Representative"</em> means any individual
									named by a Party who will act as the liaison with the other
									Party for communications relating to the Purchase Order or
									Contract, otherwise known as "Supplier Designated
									Representative" and "Buyer Designated Representative". Each
									Designated Representative will be identified to the Parties in
									writing and may, as necessary, appoint a further designee in
									writing.
								</P>
								<P>
									<em>"Material Breach"</em> means a breach by a Party of: (i)
									the confidentiality, privacy, intellectual property rights or
									data security provisions of the Purchase Order or Contract, or
									(ii) a breach of another provision of this Purchase Order or
									Contract that has a material impact on the value or benefit
									the non-breaching Party derives from this Contract.
								</P>
								<P>
									<em>"Personal Data"</em> means any information relating to an
									identified or identifiable person.
								</P>
								<P>
									<em>"Processing"</em> means any operation or set of operations
									which is performed upon Personal Data, whether or not by
									automatic means, such as collection, recording, organization,
									storage, adaptation or alteration, retrieval, consultation,
									use, disclosure by transmission, dissemination or otherwise
									making available, alignment or combination, blocking, erasure
									or destruction ("Process", "Processes" and "Processed" shall
									have the same meaning).
								</P>
								<P>
									<em>"Purchase Order"</em> means the document describing and
									authorizing the purchase of Goods or Services, issued to
									Supplier by Buyer and includes the terms and conditions of
									purchase.
								</P>
								<P>
									<em>"Statement of Work"</em> means a detailed description of
									Goods or Services as may be provided by Supplier to Buyer
									pursuant to the Contract, and agreed to by the Parties,
									including without limitation the type and scope of the
									project, authorized service providers, hourly billable rate
									for services or price quoted for the project, estimated time
									for the commencement and completion of the project, milestone
									dates and projected accomplishments by such dates,
									deliverables, and reporting procedures for tracking and
									communicating the progress of the Services.
								</P>
								<P>
									<em>"Services"</em> means the professional services to be
									provided by Supplier, as described in more detail in a
									Statement of Work, Order Form, Change Order or other
									authorized documentation incorporated into the Contract, and
									Supplier's obligations under the Contract.
								</P>
								<P>
									<em>"User"</em> means, as applicable, a person who is
									authorized to access and use, and who accesses and uses, any
									software or platform provided pursuant to or related to a
									Contract.
								</P>
							</div>
						</li>

						{/* 3 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								CONTRACTUAL DOCUMENT
							</p>
							<P>
								The Contract expressly governs and limits Supplier's acceptance
								to the terms of the Purchase Order. Any different or additional
								terms contained in any proposal or agreement provided by
								Supplier, or response by Supplier to the Contract provided by
								Buyer, are void and do not form a part of the Contract unless
								such terms are expressly accepted in a written Amendment or
								Change Order to the Contract, signed by authorized
								representatives of both Parties.
							</P>
						</li>

						{/* 4 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								PURCHASE ORDER
							</p>
							<P>
								Supplier may accept a Purchase Order by written acknowledgment
								or by commencing performance thereunder. Supplier's commencement
								of performance of a Purchase Order shall be deemed an acceptance
								by Supplier of all terms and conditions set forth in the
								Purchase Order. No amendment, addition, modification or waiver
								of the Purchase Order or any provision of its terms and
								conditions shall be binding upon Buyer or Supplier unless it is
								in writing and signed by authorized representatives of both
								Parties.
							</P>
						</li>

						{/* 5 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								PRICES AND FORM OF PAYMENT
							</p>
							<P>
								The prices reflected in each Purchase Order, Statement of Work
								or Order Form shall be identified as (i) fixed, firm and
								definitive or (ii) time and materials. Each Purchase Order,
								Statement of Work or Order Form shall clearly delineate those
								Deliverables which are for a fixed fee and those which are
								payable based on time and materials, which in the latter case
								shall include hourly rates and an estimate of total and not to
								exceed hours to complete performance. Buyer and Supplier hereby
								acknowledge that there is no index or formula pricing. The price
								stated in the Purchase Order, Statement of Work or Order Form
								shall be understood as including all items which make up the
								cost of the Goods or Services subject to the Purchase Order,
								Statement of Work or Order Form including, without limitation
								fees, insurance, consumable goods, Supplier's raw materials or
								third-party costs, transport, packing and labelling,
								accessories, devices, necessary tools, any type of expenses,
								payments for intellectual property, costs deriving from
								inspections, tests and other certificates specified in the
								Purchase Order, Statement of Work or Order Form, exchange rates,
								sales, use or excise tax, duties or import fees or tariffs.
							</P>
						</li>

						{/* 6 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								INVOICES
							</p>
							<P>
								Unless otherwise specified in the Purchase Order, Statement of
								Work or Order Form, Supplier shall invoice Buyer for delivered
								Goods or Services on the first (1st) day of each month following
								the month in which the Goods or Services were delivered, or on
								the next working day whenever the first day of the month falls
								on a weekend or federal holiday. Invoices shall specify the
								Purchase Order number under which the Goods or Services were
								purchased. Invoices shall be accompanied by any other supporting
								documentation reasonably requested by Buyer. No invoices shall
								be processed for Goods or Services which do not comply with the
								requirements of the Purchase Order or Contract. Unless otherwise
								stated in a Purchase Order, Statement of Work or Order Form,
								payment to Supplier shall be net forty-five (45) days of Buyer's
								receipt of an undisputed invoice.
							</P>
						</li>

						{/* 7 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								TIMELY DELIVERY AND ACCEPTANCE OF GOODS AND SERVICES
							</p>
							<P>
								Unless otherwise specified in the Purchase Order, Statement of
								Work or Order Form, delivery of Goods shall be Delivery Duty
								Paid ("DDP") to the location indicated by Buyer. Supplier shall
								provide, upon delivery of Goods, a delivery note showing the
								Purchase Order number, quantity, price, part number, date of
								delivery, and, where appropriate, any remarks and any other
								documentation referred to in the Purchase Order. Title and risk
								of loss to Goods (including Goods supplied as part of Services)
								shall pass to the Buyer upon Delivery. Delivery of Goods shall
								take place at the moment the delivery is made to the Buyer's
								location and signed for by Buyer's designated employee, but such
								delivery shall not confer acceptance of Goods by Buyer. No
								inspection, test, delay or failure to inspect or test, or
								failure to discover any defect or non-conformance shall relieve
								Supplier of any of its obligations or prevent a subsequent
								rejection of Goods by Buyer.
							</P>
							<P>
								Delivery of Services shall be deemed complete when all Services
								have been satisfactorily completed as confirmed by Buyer.
							</P>
							<P>
								The delivery dates specified in any Purchase Order or delivery
								schedule stated on any Statement of Work or Order Form shall be
								of the essence. Supplier shall immediately notify Buyer in
								writing of any incident or cause which prevents delivery of
								Goods or Services on the dates scheduled, specifying the reason
								for delay and if possible the estimated revised delivery date.
								If Supplier fails to so notify Buyer, Buyer shall be entitled to
								compensation for any additional actual, substantiated costs or
								expenses incurred by Buyer that could have been avoided if
								Supplier had properly notified Buyer. Supplier shall, at no
								extra cost to Buyer, take all necessary actions (including
								overtime work, urgent freight etc.) to reduce the delay period
								to a minimum and to mitigate the impacts thereof to Buyer.
								Whenever Supplier, for reasons not attributable to a force
								majeure event, does not meet the established delivery date for
								Goods or Services, Buyer shall be entitled to receive liquidated
								damages, notwithstanding and in addition to all other remedies
								available to Buyer, at the rate of two percent (2%) of the value
								of the delayed Goods or Services for each complete week of delay
								up to a maximum of ten percent (10%) of the total value of the
								delayed Goods or Services. If delay in delivery is such that
								Buyer is entitled to maximum penalty and if the Goods or
								Services still are not delivered, Buyer may terminate the
								Purchase Order or Contract in whole or in part without penalty.
								In no event shall Buyer be prevented from exercising termination
								rights under the Purchase Order or Contract during any delay
								period.
							</P>
							<P>
								All of Supplier's work shall be subject to acceptance by Buyer.
								Unless otherwise set forth in a Purchase Order or Contract, the
								acceptance period shall be thirty (30) days from Buyer's receipt
								of the Goods or Services. Supplier's Goods and Services will be
								accepted if they meet the requirements of the Purchase Order or
								Contract. Unless otherwise set forth in a Purchase Order or
								Contract, acceptance procedures will be as follows: i) Fixed Fee
								Goods and Services: following Buyer's receipt of Deliverables,
								Buyer will verify, in its reasonable discretion, that each
								Deliverable conforms in all material respects to the
								specifications set forth in the applicable Purchase Order or
								Contract. Acceptance of Deliverables that meet such
								specifications shall not be unreasonably withheld, delayed or
								conditioned by Buyer; (ii) Time and Materials Services
								Engagement: when payment for the Services is on a time and
								materials basis, Services will be deemed accepted upon
								performance, provided that Services are compliant with the
								professional services warranty as set forth in the Purchase
								Order or Contract. Notwithstanding the foregoing, acceptance
								does not preclude or waive any future warranty claim by Buyer;
								(iii) Constructive Acceptance. if Deliverables are provided on a
								time and materials basis, with acceptance upon performance, or
								another acceptance right upon performance or delivery is set
								forth in a Purchase Order, Statement of Work or Order Form,
								Buyer's acceptance of Supplier Deliverables shall be deemed to
								have occurred if Buyer does not: (a) notify Supplier to the
								contrary in writing within thirty (30) days from the date the
								Deliverable was delivered to Buyer, and (b) specify in
								reasonable detail all deficiencies and nonconformities in the
								Deliverable of which Buyer knows or should know through
								reasonable inspection following Buyer's inspection of each
								Deliverable.
							</P>
						</li>

						{/* 8 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								BUYER-SUPPLIED MATERIALS
							</p>
							<P>
								Whenever it is expressly agreed that Buyer will provide certain
								of its materials, components or content necessary for Supplier
								to perform under the Contract (the "Buyer Materials"), Buyer
								shall retain sole title to such Buyer Materials. As applicable,
								Buyer provides to Supplier a non-exclusive, non-transferable,
								fully paid, worldwide, revocable license to use Buyer Materials
								exclusively for performance of the Contract. Supplier shall
								carry out all actions necessary to safeguard Buyer's title to
								such Buyer Materials, especially in the event of any bankruptcy
								procedures involving Supplier, and Supplier shall waive any
								rights of defense arising from a bailment. Supplier represents
								that no third party or financial institution has the right to
								encumber the consigned or licensed Buyer Materials as of
								conveyance and at any time when Materials are in possession of
								Supplier. If Supplier requires Buyer Materials from Buyer in
								order to provide Goods or Services, Supplier must request such
								Buyer Materials sufficiently in advance to allow Supplier to
								meet the agreed upon delivery schedule. Supplier shall establish
								the controls necessary to maintain custody and the integrity of
								the Buyer Materials. Supplier shall store the Buyer Materials at
								its own cost, mark the same as the property of Buyer, and keep
								them separate from other materials or products. Risk of damage
								or loss to the Buyer Materials shall pass to Supplier upon
								delivery to Supplier.
							</P>
						</li>

						{/* 9 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								WORKS MADE FOR HIRE FOR BUYER
							</p>
							<P>
								Any written, visual, auditory or other materials in any format,
								including without limitation any and all forms of electronic
								media, that Supplier delivers to Buyer as, or intrinsic to, or
								included with the Deliverables, inventions and processes,
								products or services held as trade secrets, inventions for which
								applications for patents may be filed in any country, or written
								data and software and any other works of authorship that are
								protectable by copyright, shall be considered "works made for
								hire" within the meaning of applicable United States law. Works
								made for hire will include without limitation all original works
								of authorship prepared or developed by Supplier for Buyer, such
								as data, notes, technical information, business information,
								specifications, drawings, records, computer program enhancements
								and software code and related documentation. All such
								Deliverables will be the exclusive property of Buyer and Buyer
								shall be the sole owner of any and all copyrights, patent rights
								and other intellectual property rights in such Deliverables. If
								by operation of law any such Deliverables may not be considered
								as works made for hire, Supplier hereby assigns all right, title
								and ownership interest in the Deliverables to Buyer. Supplier
								agrees to execute such documents of assignment as Buyer may
								reasonably request to evidence, perfect or affect the transfer,
								recordation or protection of such Deliverables. Supplier shall
								not make the Deliverables available to any third party.
							</P>
							<P>
								Supplier will assist Buyer in every reasonable way during and
								subsequent to the term of the Purchase Order or Contract to
								obtain for Buyer's benefit, all patents, copyrights, trademarks
								or trade secret protection for such inventions, innovations,
								works of authorship, programs, know-how and techniques that
								Supplier may develop, create or participate in the development
								or creation of in the course of performing under this Purchase
								Order or Contract.
							</P>
							<P>
								Supplier is responsible for obtaining in writing all rights,
								assignments, and permissions from any subcontractors,
								individuals, or entities assisting Supplier in the execution of
								the Purchase Order or Contract or whose materials will be used
								in the execution of the Purchase Order or Contract, and shall
								deliver to Buyer a copy of all such writings. Supplier shall
								also be responsible for paying any fees owed to such
								subcontractors, individuals, or entities. Supplier agrees to
								indemnify and hold Buyer harmless against any loss, damage,
								expense, or cost, including reasonable attorneys' fees, arising
								out of any claim, demand or suit asserting that any materials or
								Deliverables delivered to Buyer by Supplier infringe any
								copyright, patent, trade secret, trademark, or other right.
							</P>
							<P>
								Notwithstanding the above, any proprietary tools, techniques,
								processes, materials, systems, generalized ideas, concepts,
								know-how, methods or skills, in any format, which Supplier
								possessed prior to initiating work on a Buyer Purchase Order or
								Contract, or that otherwise are intrinsic to Supplier's
								business, or that is provided in the same or substantially
								similar form to multiple customers of Supplier ("Supplier IP"),
								shall be and remain the sole property of Supplier. Supplier
								hereby grants to Buyer a non-exclusive, non-transferable,
								irrevocable, world-wide, permanent, fully paid license to use,
								copy, modify, sublicense and display such Supplier IP as the
								same are incorporated into Supplier's Deliverables for Buyer. As
								applicable, Supplier will disclose to Buyer the Supplier IP that
								will be used in or with the Deliverables delivered to Buyer and
								will clearly delineate any instances where Supplier IP will be
								used with, but not be included in the Deliverables. Further,
								Supplier will identify to Buyer instances where it is embedding
								or using third party intellectual property in or with the
								Deliverables delivered to Buyer, including without limitation
								software, open source tools, commercial tools, frameworks,
								accelerators, or libraries.
							</P>
						</li>

						{/* 10 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								QUALITY
							</p>
							<P>
								Supplier shall be responsible for the quality of the Goods or
								Services delivered to Buyer, regardless of whether Supplier
								manufactured or executed them itself or acquired them from a
								subcontractor. Goods and Services shall conform to the
								requirements set out in the documentation, drawings,
								specifications and regulations provided to Supplier and referred
								to in the Purchase Order, Statement of Work or Order Form. No
								technical modifications shall be made without the prior written
								consent of Buyer. Buyer shall notify Supplier in writing of any
								quality non-conformity detected by Buyer or its customers in
								Goods and Services supplied by Supplier. Supplier shall promptly
								respond to a non-conformity report or similar document issued by
								Buyer and shall promptly investigate and inform Buyer of the
								cause of the nonconformity and the corrective measures taken to
								correct it. Any other changes shall be notified in writing to
								Buyer for information purposes.
							</P>
						</li>

						{/* 11 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								SERVICE LEVELS
							</p>
							<P>
								As applicable, in the case of digital Services, platforms or
								tools requiring Supplier support, and unless otherwise agreed by
								the Parties in writing, Supplier shall abide by Buyer's minimum
								Service Level Requirements, located at{" "}
								<a
									className={lc}
									href="https://www.pmi.org/-/media/pmi/documents/public/pdf/governance/pmi-service-level-agreement.pdf"
									rel="noopener noreferrer"
									target="_blank"
								>
									PMI Service Level Agreement
								</a>
								.
							</P>
						</li>

						{/* 12 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								SUPPLIER PERSONNEL
							</p>
							<P>
								Supplier shall provide competent and qualified personnel in
								sufficient numbers to perform the Services and provide the
								Deliverables required by each Contract. Supplier personnel shall
								perform such Services and/or provide such Deliverables in
								accordance with the terms of the Purchase Order or Contract.
								Supplier personnel performing the Services on Buyer's premises
								shall comply with Buyer's rules and regulations pertaining to
								security of and access to Buyer's premises and facilities of
								which Supplier has been informed in writing. Buyer reserves the
								right to review background, qualification and geographic
								location information with respect to any Supplier personnel
								assigned to work on Buyer matters, and Supplier shall provide
								such information in full upon request. Buyer retains the right
								to have Supplier personnel removed upon reasonable written
								request.
							</P>
						</li>

						{/* 13 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								SCOPE CHANGE AND CHANGE ORDERS
							</p>
							<P>
								Buyer may request changes that affect the scope or duration of
								the Services. If Buyer requests such a change, or if Supplier
								notifies Buyer of issues or circumstances beyond the applicable
								scope of Services that may require a change, then the Parties
								shall negotiate promptly and in good faith a reasonable and
								equitable adjustment in the applicable scope, fees or deadlines.
								Unless Buyer directs Supplier to stop work pending acceptance of
								such change, Supplier shall continue work pursuant to the
								existing Purchase Order, Statement of Work or Order Form, and no
								change shall be implemented unless accepted in writing by both
								Parties. Any and all such changes once agreed to and signed by
								the Parties will be reflected in written Change Orders,
								Amendments or Addenda to the applicable Purchase Order,
								Statement of Work or Order Form.
							</P>
						</li>

						{/* 14 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								WARRANTIES
							</p>
							<P>
								In addition to any warranties made by Supplier in its brochures,
								catalogues, sales materials or other documentation, Supplier
								represents and warrants to Buyer that: (i) the Goods or Services
								it provides to Buyer are free from any defect in design,
								workmanship, raw material or manufacture; (ii) the Goods or
								Services conform to the specifications, drawings, samples or
								other descriptions applicable thereto; (iii) any Services are
								performed in a professional and workmanlike manner; (iv) any
								Goods are merchantable; (v) the Goods are new and of quality,
								unless otherwise specified by Buyer; (vi) Supplier has conveyed
								to Buyer good and unencumbered title to the Goods or Services;
								and (vii) the Goods or Services comply with applicable local,
								state, federal laws and international legislation, and domestic
								industry-recognized standards currently applicable to such Goods
								or Services. The term of such warranty (the "Warranty Period")
								shall be as set forth in the applicable Purchase Order,
								Statement of Work or Order Form and if not so specified, one (1)
								year from the date of delivery of the Goods or Services to
								Buyer.
							</P>
							<P>
								If during the Warranty Period any of the Goods or Services
								delivered by Supplier do not meet the warranties specified
								herein or otherwise applicable, Buyer may, at its option, (i)
								require Supplier to correct any defective or non-conforming
								Goods or Services at Supplier's expense; (ii) if Supplier fails
								to timely correct any defect or nonconformity, correct such
								defect and charge the expense of such correction to Supplier;
								(iii) obtain a refund from Supplier for any defective or
								non-conforming Goods or Services and return such Goods or
								Services to Supplier at Supplier's expense; or (iv) obtain cover
								Goods or Services and charge the additional costs incurred in
								obtaining such cover Goods or Services to Supplier. Such
								remedies are in addition to other remedies available to Buyer at
								law or equity and are not exclusive. Any warranties made by
								Supplier shall run to Buyer and be freely assignable to Buyer's
								successors, affiliates, assignees, financing parties, and
								customers without any requirement for Supplier's consent.
								Supplier shall assign warranties made by other parties on or
								before the commencement of the Warranty Period, including its
								vendors and suppliers, to Buyer to the fullest extent permitted
								by contract and applicable law.
							</P>
						</li>

						{/* 15 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								INDEPENDENT CONTRACTOR STATUS AND INDEMNIFICATION
							</p>
							<P>
								The relationship of Supplier to Buyer is that of an independent
								contractor. Nothing contained in the Purchase Order or Contract
								shall create an agency or employer-employee relationship between
								Buyer and Supplier. Supplier's employees shall not be considered
								employees of Buyer for any purpose. Supplier represents and
								warrants that it abides by all applicable laws with respect to
								its employees, and agrees that it shall be solely liable for any
								breach of its contractual or legal responsibilities to its
								employees, agents, suppliers or subcontractors, including
								without limitation legal or contractual requirements relating to
								health and safety requirements, immigration rules and
								documentation, worker's compensation, wage and hour,
								non-discrimination, benefits and insurance obligations. Supplier
								is solely and exclusively responsible for any claims or lawsuits
								filed by its employees or subcontractors, and shall, without any
								limitations, defend, indemnify and hold Buyer (and any relevant
								Buyer Affiliate) harmless from and against any claim,
								proceeding, action, fine, loss, cost, damages and expenses
								arising out of or relating to any such claims or lawsuits, and
								any noncompliance with legislation, regulations, codes of
								practice, guidance and other requirements of any relevant
								government or governmental agency applicable to Supplier, its
								employees or subcontractors.
							</P>
						</li>

						{/* 16 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								INSURANCE
							</p>
							<P>
								Supplier and its subcontractors shall procure and maintain
								insurance for the duration of the performance of the Purchase
								Order, Statement of Work or Order Form consisting of worker's
								compensation, employer's liability, comprehensive general and
								commercial liability, including bodily injury and property
								damage insurance, and property damage insurance for any
								equipment that may be brought to Buyer's facilities, in no less
								an amount than two million dollars ($2,000,000.00) of coverage
								per incident with respect to the general and commercial
								liability policies. In addition, and as applicable, Supplier is
								required to maintain appropriate levels of Technology Errors and
								Omissions Liability Insurance and Commercial Blanket Bond,
								including Electronic & Computer Crime or Unauthorized Computer
								Access Insurance commensurate with the type of data it secures
								under the Contract. Consultant shall provide certificates of
								insurance or other acceptable written proof of coverage to Buyer
								upon Buyer's request. All policies will keep reasonable limits
								according to the risk of the activity and any third-party
								requirements and be provided by insurance companies of a
								reputable solvency. Supplier shall name Buyer as an additional
								insured and include a waiver of subrogation against the Buyer
								when the additional insured status is forbidden by law, for the
								duration of the Purchase Order, Statement of Work or Order Form.
								Insurance maintained pursuant to this clause shall be considered
								primary as respects the interest of Buyer and is not
								contributory with any insurance which Buyer may carry.
							</P>
						</li>

						{/* 17 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								MUTUAL INDEMNIFICATION
							</p>
							<P>
								Supplier and Buyer each shall defend, indemnify and hold the
								other and its directors, officers, employees, assignees, agents,
								and affiliates harmless from any and all claims, demands, suits,
								obligations, liabilities, damages, losses and judgments,
								including costs and expenses related thereto (including
								reasonable attorney's fees), to the extent arising from actions
								or omissions of the indemnifying party, its employees, agents,
								contractors, suppliers or other representatives that include,
								cause or relate to: (i) the death or bodily injury to any person
								or damage to property on account of: (a) any alleged or actual
								defect, whether latent or patent, in any Good or Service
								provided hereunder, or (b) the actual or alleged negligence or
								intentional misconduct of the indemnifying party or any agent,
								employee, subcontractor or consultant thereof; (ii) the
								indemnifying party's actual or alleged infringement of any
								patent, trademark, copyright, or misappropriation of any trade
								secret, or infringement of any other intellectual property
								right; (iii) any claims or liabilities for royalties, liens or
								any other encumbrances on the Goods or Services supplied; (iv)
								any actual or alleged violation of the data confidentiality,
								privacy or security requirements of the Purchase Order or
								Contract; or (v) any actual or alleged breach of a Party's
								contractual or legal obligations to its employees, agents,
								consultants or subcontractors.
							</P>
						</li>

						{/* 18 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								CONFIDENTIALITY
							</p>
							<P>
								Buyer and Supplier each agree to keep confidential all
								non-public information provided by the other Party which the
								receiving party knows or reasonably should know to be
								confidential or proprietary information or documentation of the
								disclosing party, including without limitation information
								related to a Party's finances, business plans, strategic plans,
								customers, products in development, employees, or vendors
								(collectively, "Confidential Information") The Parties may
								disclose Confidential Information to those employees, agents or
								subcontractors with a need to know in order to fulfil
								obligations under the Contract or any Purchase Order; provided
								that the Parties shall be responsible for any breach of
								confidentiality obligations by such employees, agents or
								subcontractors. In the event that a Party is requested or
								required in legal, regulatory or other administrative
								proceedings to disclose any Confidential Information, the Party
								receiving the request shall promptly notify the other Party of
								such request or requirement prior to disclosure so that the
								disclosing party may seek an appropriate protective order, or
								waive compliance with the terms of this clause, as applicable.
							</P>
						</li>

						{/* 19 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								DATA PRIVACY AND SECURITY
							</p>
							<P>
								Supplier represents and warrants that it maintains appropriate
								administrative, physical and technical safeguards to protect the
								confidentiality, integrity and security of its customers' data,
								including without limitation personally identifiable information
								and other sensitive data. Supplier affirms that it meets or
								exceeds the required administrative, physical and technological
								security safeguards for the type of data Supplier processes
								under this Agreement. Supplier further represents and warrants
								that it is in compliance with the requirements of all applicable
								data protection laws in connection with its provision of Goods
								or Services. Supplier agrees to comply with the requirements of
								Buyer's Data Processing Agreement for data processors located at{" "}
								<a
									className={lc}
									href="/about/purchasing-terms-and-conditions/data-processing-agreement"
								>
									www.pmi.org/privacy/DPA
								</a>{" "}
								with respect to Supplier's processing of any and all data either
								containing personally identifiable information of an individual,
								or that could be used to determine the identity of an
								individual, when Buyer is the data controller and the data
								subjects include any employee, agent, customer or prospective
								customer of Buyer.
							</P>
						</li>

						{/* 20 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								FORCE MAJEURE
							</p>
							<P>
								Neither Party shall be deemed to be in default of any provision
								of the Purchase Order or Contract, nor be liable for any delay,
								failure in performance or interruption of services, resulting
								from acts of God, embargoes, quarantines, civil or military
								authority, civil disturbance, insurrection, war, other
								catastrophes or any such other cause beyond its reasonable
								control; provided, however, that each Party shall exercise
								reasonable efforts to remedy or mitigate any delay or impediment
								to performance to the best of its ability. The Party claiming a
								force majeure event shall notify the other Party of such event
								within five (5) calendar days of its commencement. Such notice
								shall describe the force majeure event, its estimated duration,
								its estimated impact on the notifying Party's ability to perform
								under the Contract or Purchase Order, and the measures the
								notifying Party proposes to adopt to resolve or to mitigate the
								adverse consequences arising from the force majeure event.
								Whenever a force majeure event occurs, the timing for
								performance under the Purchase Order or Contract shall be
								extended for a period equivalent to the duration of the force
								majeure event, except that if the force majeure event persists
								for more than sixty (60) days or it is or becomes apparent that
								the force majeure will persist more than sixty (60) days, the
								Party not affected by such event shall be entitled to terminate
								the Purchase Order or Contract by notifying the other Party.
								Additionally, Buyer shall be entitled to terminate the Purchase
								Order or Contract within less than sixty (60) days after the
								commencement of a force majeure event if it becomes apparent,
								within Buyer's sole reasonable judgment, that the Purchase Order
								or Contract will fail of its original purpose and the value of
								the Goods or Services to Buyer will be materially reduced as a
								consequence of a force majeure event that cannot be remediated
								or resolved promptly.
							</P>
						</li>

						{/* 21 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								SEVERABILITY
							</p>
							<P>
								If any provision of the Purchase Order or Contract shall be
								declared illegal, void or otherwise unenforceable, the remaining
								provisions shall remain in full force and effect and valid. The
								Parties shall replace any clause which is declared invalid or
								void with another valid clause which is as similar as possible
								to the original in terms of purpose and effect.
							</P>
						</li>

						{/* 22 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								TERM AND TERMINATION
							</p>
							<P>
								This MTC shall remain in effect during any time when Supplier is
								providing Goods or Services to Buyer. Except as otherwise set
								forth below, this MTC shall expire according to their own terms
								upon provision by Supplier of the last of any Goods or Services
								to Buyer.
							</P>
							<P>
								Buyer or Supplier may totally or partially cancel the Contract
								or a Purchase Order, without incurring any cost, by providing
								thirty (30) days' advance written notice to the defaulting party
								of the defaulting event, in any of the following cases: (i)
								material breach by the defaulting party of the Purchase Order or
								Contract; (ii) whenever either Party becomes unincorporated or
								is declared bankrupt, insolvent or in receivership; (iii) any
								legal situation which limits the capacity of either Party to
								manage or dispose of its assets and which negatively affects its
								compliance with its obligations under the Purchase Order or
								Contract (including but not limited to being unable to pay its
								debts, passing a resolution for its winding up or a court of
								competent jurisdiction ordering the Party to be wound up or
								dissolved, the appointment of an administrator of or the making
								of an administration order or the appointment of a receiver or
								an administrative receiver).
							</P>
							<P>
								Buyer may totally or partially cancel the Purchase Order or
								Contract, without incurring any cost, by providing thirty (30)
								days' advance written notice to Supplier in any of the following
								cases: (i) whenever, in the sole opinion of Buyer, delays in the
								manufacturing, assembly or delivery of Goods or Services could
								prevent Supplier from meeting the delivery times, quality
								levels, requirements or material project deadlines specified in
								the Purchase Order or Contract; (ii) Buyer has determined in its
								sole judgment that the Goods or Services do not meet expected
								standards of quality or efficacy or otherwise do not meet
								Buyer's reasonable expectations; (iii) in the event that there
								is a material change in Buyer's strategy, business plan, market
								assessment, risk assessment, financial condition, or other
								change which in Buyer's sole judgment requires termination of
								the Purchase Order or Contract; (iv) the event of a "Change of
								Control" of Supplier. For the purposes of this Clause "Change of
								Control" means the likelihood of one or more persons acting
								together taking the control of Supplier so that, in the
								reasonable opinion of Buyer, its interests are adversely
								affected. Such "Change of Control" shall take place when, after
								the direct or indirect acquisition of Supplier, Supplier belongs
								to the same group as the acquirer or acquirers of its shares
								according to applicable law.
							</P>
						</li>

						{/* 23 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								ASSIGNMENT
							</p>
							<P>
								Either Party may assign a Contract with the prior written
								consent of the other Party. An assignment without such consent
								shall be void.
							</P>
						</li>

						{/* 24 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								NO GRATUITIES OR COMMISSIONS
							</p>
							<P>
								Supplier understands that Buyer prohibits its employees,
								contractors and representatives from accepting gifts from
								Suppliers and prohibits its Suppliers from offering anything of
								material value to Buyer employees, contractors and
								representatives, as well as to third parties, in connection with
								its provision of Goods and Services to Buyer. Supplier
								represents and warrants that it, including its agents,
								subcontractors or other representatives, has not given and will
								not give any material gift or gratuity, nor has it agreed and
								will not agree to pay any commission, bonus or other payment,
								nor provide anything of material value, to any of Buyer's
								employees, agents or representatives, nor to any third party, in
								connection with any Purchase Order or Contract. In the event of
								any breach of the foregoing provisions, Buyer may terminate the
								relevant Purchase Order or Contract and recover from Supplier
								any losses suffered by Buyer as a result of (i) such termination
								and (ii) the breach of any obligation under this paragraph,
								whether or not the Purchase Order or Contract has been
								terminated.
							</P>
						</li>

						{/* 25 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								CONFLICT OF INTEREST
							</p>
							<P>
								Supplier warrants they have no conflict of interest with their
								provision of products and/or services to the Buyer. Supplier
								must avoid any situation or relationship that may involve an
								inappropriate conflict or the appearance of a conflict with the
								interests of Buyer. Buyer employees and their family members may
								not hold any significant economic interest in any entity that
								does business with Buyer and Supplier is required to avoid such
								relationships with Buyer employees. Should a Conflict of
								Interest arise during the provision of products and/or services
								to the Buyer, Supplier shall notify Buyer promptly in writing.
							</P>
						</li>

						{/* 26 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								CORPORATE SOCIAL RESPONSIBILITY
							</p>
							<P>
								Buyer considers observance of human rights and
								non-discrimination laws to be a key component of its and its
								suppliers' corporate social responsibilities. Accordingly,
								Supplier undertakes: (i) not to admit to employment, directly or
								indirectly, anyone below the minimum age as defined in the
								International Labour Organisation Convention No.138 (ILO); (ii)
								not to apply, directly or indirectly, forced labor or any means
								of labor under duress; (iii) not to apply, amongst its
								employees, physical punishment, threats of violence nor any
								other means of duress or physical or mental abuse; and (iv) to
								avoid any kind of unlawful discrimination against or among its
								employees, meaning any distinction, exclusion or preference
								giving rise to duress or inequality based on race, color, sex,
								religious belief, political opinion, nationality, gender
								expression, sexual orientation, disability or any other
								personal, physical or social condition, or other status
								protected by law. If Supplier is found to be in breach of any of
								the foregoing provisions, Buyer shall take the measures it
								considers appropriate, including the suspension or termination
								of the Purchase Order or Contract.
							</P>
						</li>

						{/* 27 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								COMPETIVENESS
							</p>
							<P>
								Supplier will use its best efforts to assure that all Contract
								Goods and Services remain competitive in terms of current
								technology, design, and quality and price with similar goods
								available to Buyer up to the date of delivery. If, in the sole
								opinion of Buyer, any such items do not remain competitive as
								defined above, Buyer, to the extent it is free to do so, will
								notify Supplier of the area(s) in which other goods are more
								competitive. If, within thirty (30) days, Supplier does not
								agree to timely sell such items with comparable technology,
								design or quality or, if applicable, at a competitive price,
								Buyer may terminate the applicable Purchase Order, Statement of
								Work or Order Form and purchase the applicable items from
								another supplier without liability to Supplier.
							</P>
						</li>

						{/* 28 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								FAR FLOWDOWN PROVISIONS UNDER A U.S. GOVERNMENT PRIME CONTRACT
							</p>
							<P>
								Supplier acknowledges and agrees that (i) the additional terms
								located at{" "}
								<a className={lc} href="/terms/far">
									www.pmi.org/terms/far
								</a>{" "}
								("Government Contracting Terms") are hereby incorporated into
								this MSA by reference and will apply to this MSA as if set forth
								in full herein, (ii) Supplier (and, to the extent applicable,
								its subcontractors) will comply with all such Government
								Contracting Terms, and (iii) PMI may modify such Government
								Contracting Terms at any time and in its sole discretion, and
								such modified Government Contracting Terms will be incorporated
								into and apply to this MSA.
							</P>
						</li>

						{/* 29 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								NOTICES
							</p>
							<P>
								Any notices to be given by either Party to the other may be done
								by personal delivery, recognized overnight courier or by mail,
								registered or certified, postage prepaid with return receipt
								requested. Mailed notices shall be addressed to the Parties at
								the addresses appearing in the applicable Purchase Order or
								Contract. All notices delivered personally shall be deemed
								communicated as of the date of actual receipt; notices delivered
								by overnight courier or mail shall be deemed communicated as of
								the date recorded on the delivery receipt. For purposes of this
								Purchase Order or Contract, "personal delivery" includes notice
								transmitted by fax or electronic mail, provided sender maintains
								confirmation that the notice was properly transmitted on that
								date.
							</P>
						</li>

						{/* 30 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								SURVIVAL OF TERMS
							</p>
							<P>
								All provisions which must survive termination of the Contract or
								a Purchase Order to be effective shall survive termination. The
								following provisions specifically shall survive the expiration
								or termination of the Contract or a Purchase Order: Prices and
								Form of Payment, Warranties, Environmental Requirements,
								Indemnification, Confidential Information, Privacy, Applicable
								Law and Jurisdiction, and Proprietary Rights.
							</P>
						</li>

						{/* 31 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								APPLICABLE LAW AND JURISDICTION
							</p>
							<P>
								Supplier's provision of Goods or Services to Buyer shall be
								governed by and shall be construed, interpreted and enforced
								according to the laws of the Commonwealth of Pennsylvania
								without regard to choice of law principles thereof. The Parties
								hereby consent to the nonexclusive jurisdiction of the state and
								federal courts of Pennsylvania over any dispute arising under
								the Purchase Order or Contract.
							</P>
						</li>

						{/* 32 */}
						<li className="space-y-3 pl-2">
							<p className="font-aeonik font-bold text-pmi-text-primary">
								ENTIRE AGREEMENT
							</p>
							<P>
								This MTC supersedes all prior agreements, oral or in writing,
								between the Parties with respect to Supplier's provision of
								Goods or Services to Buyer, and along with the applicable
								Purchase Order, Statement of Work or Order Form, contains the
								entire agreement of the Parties with respect to the subject
								matter thereof. The Parties acknowledge that no representations,
								inducements, or agreements have been made by either Party which
								are not embodied here, and that no other agreement or
								representation not contained in the Purchase Order or Contract
								is valid or binding. A modification of this MTC will be
								effective only if it is in writing and signed by authorized
								representatives of the Parties.
							</P>
						</li>
					</ol>
				</div>
			</div>
		</main>
	);
}
