name: pmigov

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    init: true
    ports:
      - "3001:3001"
    env_file:
      - path: apps/web/.env
        required: false
    environment:
      BETTER_AUTH_URL: http://localhost:3001
      CORS_ORIGIN: http://localhost:3001
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/pmigov
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:18.4-alpine3.23
    container_name: pmigov-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pmigov
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - pmigov_postgres_data:/var/lib/postgresql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=12"
      - "-c"
      - "max_slot_wal_keep_size=4GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pmigov_postgres_data:
